// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog: dynamic(() => import("./Blog")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  resme_tabs: dynamic(() => import("./ResumeTabs")),
  used_tech: dynamic(() => import("./UsedTech")),
};
